name: Hardcoded PDF ESG Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # daily at 3 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install requests pandas PyPDF2
      - run: python scraper/scraper.py
      - run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add data/ghg_records.csv
          git commit -m "Update ESG data from hardcoded PDFs [skip ci]" || echo "No changes"
          git push
